feat(core): Add support for secret key rotation
pallets-eco/flask-security pull request #1039
Opened 2024-11-15 08:36 UTC by jamesejr

This PR adds support for secret key rotation and fixes #1038

2024-11-15 15:12 UTC, jwag956 commented
This iooks great - thanks! The test failures are due to latest Flask 3.1 which I am looking into in the next few days.

2024-11-15 20:03 UTC, jwag956 requested changes
thanks

2024-11-15 20:03 UTC, jwag956 commented on docs/configuration.rst
> +    that were created with previous secret keys.
Could you add the same wording as above - that is is a Flask (>=3.1) configuration used by Flask-Security. I would also remove the 'default' since we don't control that - users should look at the Flask documentation.

2024-11-15 22:14 UTC, jamesejr commented on docs/configuration.rst
> +    that were created with previous secret keys.
Updated! Let me know what you think. Happy to change it again if you prefer something different. Thanks for the quick review!

2024-11-16 01:26 UTC, jwag956 approved these changes

2024-11-16 01:26 UTC, merged