feat(recoverable): Add support for username recovery via simple login flows
pallets-eco/flask-security pull request #1041
Opened 2024-11-18 08:32 UTC by jamesejr

PR adds support for requesting a forgotten username (closes #980). If the user requesting the username recovery enters an email that is valid, they will receive the associated username via the registered email, otherwise they will not.

2024-12-23 05:35 UTC, jamesejr commented
> In general - this is awesome and quite complete... thanks
> 
> A few minor things - the only larger issue is to make sure that JSON and GENERIC_RESPONSES are supported for the new endpoint.

@jwag956 Apologies this took me a bit longer to get back into. But I believe I addressed everything. Please take a look whenever you have a chance and enjoy your holidays!

2024-12-24 02:48 UTC, jwag956 requested changes
Wonderful! just a few more comments - only 1 substantive request...

2024-12-24 02:48 UTC, jwag956 commented on tests/conftest.py
> +    app.config["SECURITY_USERNAME_RECOVERY"] = True
nit: do this in for loop below with all the other options

2024-12-24 02:48 UTC, jwag956 commented on docs/api.rst
> +.. autoclass:: flask_security.UsernameRecoveryForm
nit: alphabetize please!

2024-12-24 02:48 UTC, jwag956 commented on docs/openapi.yaml
> +      summary: Request username recovery
Not quite complete - both request and response should have both form and JSON

2024-12-24 02:48 UTC, jwag956 commented on docs/openapi.yaml
> +            application/json:
not quite right - this looks like the response for forms - not JSON - and you need to add JSON API

2024-12-24 02:48 UTC, jwag956 commented on flask_security/__init__.py
> +    UsernameRecoveryForm,
nit: alphabetize

2024-12-24 02:48 UTC, jwag956 commented on flask_security/views.py
> +        user = _datastore.find_user(email=form.email.data)
You don't need to do this - UserEmailFormMixin already looks it up and sets form.user if email exists. So if validation succeeds - form.user will be set.

2024-12-24 02:48 UTC, jwag956 commented on flask_security/views.py
> +    if form.validate_on_submit():
I am not comfortable calling validate_on_submit twice .... as with many other views I think that on GET or POST errors - the template should be rendered (as you do). Maybe what I am  asking is - rather than this if/redirect here - do the redirect up in the validate_on_submit() part:
```
if validate_on_submit():
  send_username_recovery_email()
  if _security_want_json(request):
    return base_render_json....
  do_flash(xxx)
    return redirect(get_url(".login")
```

2024-12-24 03:02 UTC, jwag956 commented on flask_security/views.py
> +    return _security.render_template(
Please add a context_processor like all other views!

2024-12-29 17:11 UTC, jwag956 requested changes
Thanks for sticking with this - things are looking great - few even smaller things and we'll be done!

2024-12-30 03:26 UTC, jamesejr commented
Thanks again for the review @jwag956! I believe everything should be addressed now. Let me know what you think.

2024-12-30 06:01 UTC, jwag956 approved these changes
Thanks for being patient... Adding a new view has a lot of boilerplate alas..

2024-12-30 06:02 UTC, merged